// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bands": {
            "get": {
                "description": "returns a list of all bands",
                "tags": [
                    "Bands"
                ],
                "summary": "returns a list of all bands",
                "responses": {}
            }
        },
        "/bands/{bandId}": {
            "get": {
                "description": "returns a band by its id",
                "tags": [
                    "Bands"
                ],
                "summary": "returns a band by its id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "find band by id",
                        "name": "bandId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Band Service API",
	Description:      "A Band service API in Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
