name: Build and push container to acr

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Generate Docker Image PR tag
        id: docker_tag
        run: |
          GIT_SHA_SHORT=$(${GITHUB_SHA::7})
          echo "DOCKER_IMAGE_TAG=$GIT_SHA_SHORT" >> $GITHUB_OUTPUT

      - name: docker build
        run: docker build -t ${{ secrets.ACR_SERVER_LAB }}/bandapi:${{ steps.docker_tag.outputs.DOCKER_IMAGE_TAG }} .

      - name: az login
        uses: Azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: docker push
        run: |
          az acr login --name ${{ secrets.ACR_REGISTRY_LAB }}
          docker push ${{ secrets.ACR_SERVER_LAB}}/bandapi:${{ steps.docker_tag.outputs.DOCKER_IMAGE_TAG }}
          docker logout
