name: Build and push container to acr

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Generate Docker Image tag
        id: docker_tag
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Docker Build
        run: docker build -t ${{ secrets.ACR_SERVER_LAB }}/bandapi:${{ steps.docker_tag.outputs.DOCKER_IMAGE_TAG }} .

      - name: az login
        uses: Azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Push
        run: |
          az acr login --name ${{ secrets.ACR_REGISTRY_LAB }}
          docker push ${{ secrets.ACR_SERVER_LAB}}/bandapi:${{ steps.docker_tag.outputs.DOCKER_IMAGE_TAG }}
          docker logout
